const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),ts=require('typescript');
function load(file,stubs={}){const m={exports:{}};const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;vm.runInThisContext('(function(require,module,exports,process,Buffer){'+code+'\n})')(p=>p in stubs?stubs[p]:p==='server-only'?{}:require(p),m,m.exports,process,Buffer);return m.exports;}
(async()=>{
process.env.ADMIN_SESSION_SECRET='test-only-session-secret-with-enough-length';
const model=load('lib/analytics/model.ts');let commands,response=[1];
const mockRedis=async c=>{commands=c;return response;};
const conv=load('lib/analytics/conversions.ts',{'./store':{redis:mockRedis,analyticsConfigured:()=>true},'./model':model});
const c={event:'11111111-1111-4111-8111-111111111111',visitor:'22222222-2222-4222-8222-222222222222',path:'/about',label:'Discuss your project',target:'/contact'};
assert.equal(conv.validCta(c),true);
for(const patch of [{path:'/admin'},{path:'/contact?email=private'},{target:'javascript:alert(1)'},{target:'//evil.test'},{visitor:'not-id'},{label:''}])assert.equal(conv.validCta({...c,...patch}),false);
const req=new Request('https://site.test/api',{headers:{'x-forwarded-for':'192.0.2.10'}});
await conv.recordCta(c,req);assert.equal(commands[0][0],'EVAL');assert.ok(commands[0][1].includes("'NX'"));assert.ok(commands[0][1].includes('PFADD'));assert.ok(!JSON.stringify(commands).includes('192.0.2.10'));assert.ok(!JSON.stringify(commands).includes(c.visitor));
const id=c.event,details={name:'Test',email:'test@example.com',message:'Exact submitted message',goal:'SEO',company:'Example',budget:'Discuss'};
await conv.saveEnquiry(details,id,req);const payload=JSON.parse(commands[0].at(-4));assert.deepEqual(payload.details,details);assert.equal(payload.status,'new');assert.ok(commands[0][1].includes('EXISTS'));assert.ok(commands[0][1].includes('7776000'));
response=[2];assert.equal(await conv.saveEnquiry(details,id,req),id);
response=[0];await assert.rejects(()=>conv.saveEnquiry(details,id,req),/Too many/);
response=[1];assert.equal(await conv.updateEnquiry(id,'qualified','Needs proposal'),true);assert.ok(commands[0][1].includes('KEEPTTL'));
await conv.deleteEnquiry(id);assert.deepEqual(commands.map(c=>c[0]),['DEL','ZREM']);
const dates=model.reportDays(7);response=dates.flatMap(()=>[2,[JSON.stringify(['/about','CTA','/contact']),'2'],1]);response.push(4);
const report=await conv.conversionReport(7);assert.equal(report.clicks,14);assert.equal(report.clickers,4);assert.equal(report.submissions,7);assert.equal(report.ctas[0].clicks,14);assert.equal(commands.at(-1).length,8);
let signed=false,origin=true;
const api=load('app/api/admin/enquiries/route.ts',{'@/lib/admin/auth':{authenticated:async()=>signed,sameOrigin:()=>origin},'@/lib/analytics/store':{analyticsConfigured:()=>true},'@/lib/analytics/conversions':{listEnquiries:async()=>[{id,details}],updateEnquiry:async()=>true,deleteEnquiry:async()=>{}}});
assert.equal((await api.GET(req)).status,401);signed=true;
assert.equal((await api.GET(new Request('https://site.test/api?days=1'))).status,400);
assert.equal((await api.GET(req)).status,200);
origin=false;assert.equal((await api.PATCH(req)).status,403);origin=true;
const patch=(body)=>new Request('https://site.test/api',{method:'PATCH',body:JSON.stringify(body)});
assert.equal((await api.PATCH(patch({id,status:'fake',notes:''}))).status,400);
assert.equal((await api.PATCH(patch({id,status:'qualified',notes:'Next call'}))).status,200);
assert.equal((await api.DELETE(patch({id}))).status,200);
let stored=0;
const contact=load('app/api/contact/route.ts',{'next/server':{NextResponse:{json:Response.json}},'@/lib/admin/auth':{sameOrigin:()=>origin},'@/lib/analytics/conversions':{saveEnquiry:async()=>{stored++;}}});
const post=body=>new Request('https://site.test/api/contact?validate=1',{method:'POST',body:JSON.stringify(body)});
assert.equal((await contact.POST(post({...details,submissionId:id}))).status,200);assert.equal(stored,1);
assert.equal((await contact.POST(post({...details,email:'bad',submissionId:id}))).status,400);assert.equal(stored,1);
assert.equal((await contact.POST(post({...details,_honey:'bot',submissionId:id}))).status,200);assert.equal(stored,1);
origin=false;assert.equal((await contact.POST(post({...details,submissionId:id}))).status,403);
console.log('PASS: CTA validation, atomic recording, anonymous identifiers, conversion aggregation, enquiry retention/deduplication, status updates, deletion, authenticated access and contact saving.');
})().catch(e=>{console.error(e);process.exitCode=1;});
